name: Weekly build & deploy (backend→frontend→pages)

on:
  # ✅ Cron: tous les lundis à 05:00 UTC (≈ 06:00 Paris en hiver)
  schedule:
    - cron: "0 5 * * 1"
  # Déclenchement manuel
  workflow_dispatch:
  # (optionnel) build aussi sur push main
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-weekly"
  cancel-in-progress: true

jobs:
  backend:
    name: Generate export (WEEK_OFFSET=-1)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run backend (last week)
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          WEEK_OFFSET: "-1"
        run: python main.py

      - name: Show export dir
        run: |
          ls -la export
          cat export/weeks.json || true

      - name: Upload export artifact
        uses: actions/upload-artifact@v4
        with:
          name: export
          path: backend/export
          if-no-files-found: error
          retention-days: 14

  frontend:
    name: Build frontend & upload Pages artifact
    needs: backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      # ⬇️ Récupère l'export généré par le job backend
      - name: Download export artifact
        uses: actions/download-artifact@v4
        with:
          name: export
          path: frontend/public/export

      # (optionnel) vérifie que weeks.json est là
      - name: Check export presence
        run: |
          ls -la public/export
          test -f public/export/weeks.json

      - name: Build (Vite)
        # Si tu sers sous /veille/, assure base dans vite.config.ts
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    name: Deploy to GitHub Pages
    needs: frontend
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4